version: 2
jobs:
  build:
    working_directory: /go/src/github.com/trackit/trackit-server
    docker:
      - image: msolution/trackit2-circleci
    branches:
      only:
        - stg
    steps:
      - checkout
      - run:
          name: Get dependencies with govendor
          command: |
            set -xe
            govendor sync -v
      - run:
          name: Build portable binary
          command: |
            set -xe
            cd server/
            ./buildstatic.sh
      - setup_remote_docker
      - run:
          name: Copy SQL schema
          command: |
            set -xe
            pushd scripts
            ./copy_schema.sh
            popd
      - run:
          name: Build SQL Docker image
          command: |
            set -xe
            docker build -t msolution/stg-trackit2-sql docker/sql/
      - run:
          name: Build API Docker image
          command: |
            set -xe
            docker build -t msolution/stg-trackit2-api docker/server/

# vim: set ts=2 sts=2 et:
