version: '3'
services:
  sql:
    build: sql/
    environment:
      - MYSQL_USER=${TRACKIT_SQL_USER:-trackit}
      - MYSQL_PASSWORD=${TRACKIT_SQL_PASSWORD:-trackitpassword}
      - MYSQL_DATABASE=${TRACKIT_SQL_DATABASE:-trackit}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - app
    ports:
      - '127.0.0.1:3306:3306'
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass changeme"]
    networks:
      - app
    ports:
      - '127.0.0.1:6379:6379'
  api:
    build: server/
    links:
      - sql
      - redis
    command:
      - -sql-address=${TRACKIT_SQL_USER:-trackit}:${TRACKIT_SQL_PASSWORD:-trackitpassword}@tcp(sql:3306)/${TRACKIT_SQL_DATABASE:-trackit}?parseTime=true
      - -es-address=${TRACKIT_ES_ADDRESS:-http://10.20.0.10:9200}
      - -redis-address=${TRACKIT_REDIS_ADDRESS:-redis:6379}
      - -http-address=[::]:80
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - app
    volumes:
      - ../reports/output:/reports
networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.19.84.0/24

# vim: ts=2 sts=2 et:
