version: '3'
services:
  sql:
    build: sql/
    environment:
      - MYSQL_USER=${TRACKIT_SQL_USER:-trackit}
      - MYSQL_PASSWORD=${TRACKIT_SQL_PASSWORD:-trackitpassword}
      - MYSQL_DATABASE=${TRACKIT_SQL_DATABASE:-trackit}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - app
    ports:
      - '127.0.0.1:3306:3306'
  api:
    build: server/
    links:
      - sql
    command:
      - -sql-address=${TRACKIT_SQL_USER:-trackit}:${TRACKIT_SQL_PASSWORD:-trackitpassword}@tcp(sql:3306)/${TRACKIT_SQL_DATABASE:-trackit}?parseTime=true
      - -es-address=http://10.20.0.10:9200/
      - -http-address=[::]:80
      - -periodics=false
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - '127.0.0.1:8580:80'
    networks:
      - app
    volumes:
      - ../reports/output:/reports
networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.19.84.0/24

# vim: ts=2 sts=2 et:
